import { FaFacebookF, FaInstagram, FaWhatsapp } from "react-icons/fa";
import { HiOutlineArrowRight, HiOutlineMapPin, HiOutlinePhone, HiOutlineShieldCheck, HiOutlineWrenchScrewdriver } from "react-icons/hi2";

const WHATSAPP = "https://wa.me/5542988179672?text=Ol%C3%A1%2C%20SOS%20Pneus!%20Gostaria%20de%20solicitar%20um%20or%C3%A7amento.";
const services = [
  ["servico-freios-pro.png", "Freios", "Inspeção, manutenção e substituição dos componentes do sistema de frenagem."],
  ["servico-suspensao-pro.png", "Suspensão", "Diagnóstico e manutenção para estabilidade, conforto e segurança ao dirigir."],
  ["servico-oleo-pro.png", "Troca de óleo", "Óleo e filtros adequados para preservar o desempenho e a vida útil do motor."],
  ["servico-embreagem-pro.png", "Embreagem", "Avaliação e manutenção do conjunto de embreagem do seu veículo."],
  ["servico-injecao-pro.png", "Injeção eletrônica", "Diagnóstico preciso para funcionamento eficiente e economia de combustível."],
  ["servico-bicos-pro.png", "Limpeza de bicos", "Limpeza técnica para recuperar desempenho e regularidade do motor."],
  ["servico-alinhamento-pro.png", "Alinhamento e balanceamento", "Mais estabilidade, menor desgaste dos pneus e direção segura."],
  ["servico-pneus-pro.png", "Montagem e conserto de pneus", "Montagem, reparos e avaliação técnica para pneus automotivos."],
];
const products = [["produto-remold-pro.png","Pneus remold"],["produto-novos-pro.png","Pneus novos"],["produto-recapagem-pro.png","Recapagens"],["produto-agricola-pro.png","Pneus agrícolas"],["produto-empilhadeira-pro.png","Pneus para empilhadeira"],["produto-camaras-pro.png","Câmaras de ar"]];
const brands = [["greenn.png","Green Tire"],["Fm.png","FM Pneus"],["tortuga.png","Tortuga"],["bkt1.png","BKT"],["lubrax1.png","Lubrax"],["cofap1.png","Cofap"]];
const schema = { "@context":"https://schema.org", "@type":"TireShop", name:"SOS Pneus Guarapuava", url:"https://sospneus-c5925.web.app/", image:"https://sospneus-c5925.web.app/assets/logo-1.png", telephone:"+55 42 3304-8476", address:{"@type":"PostalAddress",streetAddress:"Rua Antônio Losso, 1033",addressLocality:"Guarapuava",addressRegion:"PR",postalCode:"85060-260",addressCountry:"BR"}, areaServed:"Guarapuava e região", description:"Loja de pneus, auto center, mecânica e recapagens em Guarapuava." };

export default function Home() { return <main>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} />
  <header className="header"><a className="logo" href="#inicio"><img src="/assets/logo-1.png" alt="SOS Pneus" /></a><nav><a href="#sobre">Quem somos</a><a href="#servicos">Serviços</a><a href="#produtos">Produtos</a><a href="#contato">Contato</a></nav><a className="header-cta" href={WHATSAPP} target="_blank" rel="noreferrer"><FaWhatsapp/> Orçamento</a></header>
  <section className="hero" id="inicio"><div className="hero-lines"></div><div className="hero-copy"><p className="kicker">Auto center em Guarapuava</p><h1>Seu carro seguro.<br/><em>Sua viagem tranquila.</em></h1><p>Pneus, manutenção e atendimento técnico para cuidar do seu veículo do começo ao fim.</p><div className="hero-actions"><a className="primary" href={WHATSAPP} target="_blank" rel="noreferrer">Solicitar orçamento <HiOutlineArrowRight/></a><a className="secondary" href="#servicos">Conhecer serviços</a></div><div className="hero-badges"><span><HiOutlineShieldCheck/> Segurança em primeiro lugar</span><span><HiOutlineWrenchScrewdriver/> Equipe especializada</span></div></div><div className="hero-visual"><div className="tire-ring"><img src="/assets/hero-pneus.png" alt="Conjunto de pneus automotivos novos em destaque" /></div><div className="hero-stamp"><strong>Desde<br/>2018</strong><span>em Guarapuava</span></div></div></section>
  <section className="about" id="sobre"><div className="about-mark"><span>01</span><h2>Quem<br/>somos</h2></div><div className="about-copy"><p className="lead">Muito além de uma loja de pneus: somos o auto center que acompanha você.</p><p>Fundada com o propósito de comercializar e consertar pneus, a SOS Pneus cresceu ao ouvir as necessidades dos clientes. Hoje reunimos produtos de qualidade, mão de obra capacitada e serviços completos para veículos.</p><p>Também atuamos com recapagem de pneus de carga, agrícolas e OTR em Guarapuava e região, representando uma das maiores reformadoras de pneus do Brasil.</p><div className="stats"><div><strong>2018</strong><span>Início da história</span></div><div><strong>8+</strong><span>Serviços automotivos</span></div><div><strong>3</strong><span>Linhas de recapagem</span></div></div></div></section>
  <section className="services" id="servicos"><div className="section-title"><p>O que fazemos</p><h2>Serviços para rodar<br/><em>com confiança</em></h2></div><div className="service-grid">{services.map(([img,title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><img src={`/assets/${img}`} alt=""/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="products" id="produtos"><div className="section-title light"><p>Para cada necessidade</p><h2>Produtos e soluções<br/><em>para o seu trabalho</em></h2></div><div className="product-grid">{products.map(([img,title])=><article key={title}><img src={`/assets/${img}`} alt={title}/><div><h3>{title}</h3><a href={WHATSAPP} target="_blank" rel="noreferrer">Consultar disponibilidade <HiOutlineArrowRight/></a></div></article>)}</div></section>
  <section className="brands"><div className="brands-heading"><p>Marcas e parceiros</p><strong>Qualidade de quem entende de estrada.</strong></div><div className="brand-grid">{brands.map(([img,name])=><figure key={name}><img src={`/assets/${img}`} alt={name}/><figcaption>{name}</figcaption></figure>)}</div></section>
  <section className="contact" id="contato"><div className="contact-copy"><p className="kicker">Fale com a equipe</p><h2>Seu veículo merece<br/><em>o cuidado certo.</em></h2><p>Solicite um orçamento ou venha conhecer nosso auto center em Guarapuava.</p><a className="primary red" href={WHATSAPP} target="_blank" rel="noreferrer"><FaWhatsapp/> Chamar no WhatsApp</a><div className="contact-numbers"><a href="tel:+554233048476"><HiOutlinePhone/> (42) 3304-8476</a><a href="https://wa.me/5542988179672"><FaWhatsapp/> (42) 98817-9672</a></div></div><div className="map"><iframe title="Localização da SOS Pneus em Guarapuava" loading="lazy" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3605.0609307774757!2d-51.46609235472874!3d-25.36927432554864!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ef377f43f77e2b%3A0x6de35fae02bc375b!2sSos%20Pneus%20Guarapuava%20-%20Pneus%2C%20Oficina%20e%20Troca%20de%20%C3%93leo!5e0!3m2!1spt-BR!2sbr!4v1726087141036!5m2!1spt-BR!2sbr"/><a href="https://www.google.com/maps/search/?api=1&query=SOS+Pneus+Rua+Antonio+Losso+1033+Guarapuava" target="_blank" rel="noreferrer"><HiOutlineMapPin/> Rua Antônio Losso, 1033 — Guarapuava, PR</a></div></section>
  <section className="team"><div><p>Contatos comerciais</p><h2>Nossa equipe<br/>está por perto.</h2></div><div className="team-grid"><article><span>Loja</span><a href="https://wa.me/5542988179672">(42) 98817-9672</a><a href="tel:+554233048476">(42) 3304-8476</a></article><article><span>Região de Prudentópolis</span><a href="https://wa.me/55429991296759">(42) 99912-6759</a></article><article><span>Região de Guarapuava</span><a href="https://wa.me/5542999775053">(42) 99977-5053</a></article></div></section>
  <footer><div className="footer-logo"><img src="/assets/logo-1.png" alt="SOS Pneus"/><p>Pneus, oficina e troca de óleo em Guarapuava.</p></div><div><p>Navegação</p><a href="#sobre">Quem somos</a><a href="#servicos">Serviços</a><a href="#produtos">Produtos</a></div><div><p>Redes sociais</p><a href="https://www.facebook.com/sospneusguarapuavapr" target="_blank" rel="noreferrer"><FaFacebookF/> Facebook</a><a href="https://www.instagram.com/sospneusguarapuavapr" target="_blank" rel="noreferrer"><FaInstagram/> Instagram</a></div><small>© 2026 SOS Pneus. Todos os direitos reservados.</small></footer>
  <a className="float" href={WHATSAPP} target="_blank" rel="noreferrer" aria-label="Chamar a SOS Pneus no WhatsApp"><FaWhatsapp/></a>
  </main>; }
